### ISSUE TITLE
Function to generate PBRT

### ISSUE THREAD

**Issue by rssalessio** [rssalessio/ictproject#3]
Need to make a function to generate PBRT

**Comment by gsavaia** [comment]
http://it.mathworks.com/help/ident/ref/idinput.html?refresh=true 

Do you think it's worth defining a new function? I think this one is ok.

**Comment by rssalessio** [comment]
https://github.com/rssalessio/ictproject/commit/81deafb3977f9abe9369430c9272e708b1e76f8f
